# -*- coding: utf-8 -*-
# Additional glossary terms from the deep lectures. Merged into GLOSSARY at build.
GLOSSARY_EXTRA = [
  {'term': 'Slip', 'def': "The small difference between an induction motor's synchronous speed and its actual rotor speed; without slip no torque is produced"},
  {'term': 'Synchronous Speed', 'def': 'The rotating-magnetic-field speed of an AC motor = 120 x frequency / number of poles (e.g. 1800 RPM for a 4-pole on 60 Hz)'},
  {'term': 'RMS', 'def': 'Root Mean Square - the equivalent DC value that does the same heating work as an AC waveform; what a meter displays for AC'},
  {'term': 'Power Factor', 'def': 'Cosine of the phase angle between voltage and current; how much current does real work versus just magnetizing (low PF = wasted current)'},
  {'term': 'KVL', 'def': "Kirchhoff's Voltage Law - the voltage drops around any closed loop sum to zero"},
  {'term': 'KCL', 'def': "Kirchhoff's Current Law - current into a node equals current out of it"},
  {'term': "Ohm's Law", 'def': 'V = I x R - the relationship between voltage, current, and resistance; the most-used equation in troubleshooting'},
  {'term': 'Live Zero', 'def': 'The 4 mA lower end of a 4-20 mA loop, so that 0 mA unmistakably signals a broken wire or dead transmitter'},
  {'term': 'Quadrature', 'def': 'Two encoder channels (A and B) 90 degrees out of phase; their phase order gives direction, their rate gives speed'},
  {'term': 'Absolute Encoder', 'def': 'An encoder that reports its exact position even after power loss, requiring no re-homing'},
  {'term': 'Incremental Encoder', 'def': 'An encoder that outputs pulse trains counted to track relative position, speed, and direction'},
  {'term': 'Input Image Table', 'def': 'The memory snapshot of all inputs a PLC reads at the start of each scan and uses throughout the program scan'},
  {'term': 'Last-State-Wins', 'def': 'When one output bit is written on multiple rungs, the last rung executed in a scan determines its value'},
  {'term': 'Sinking', 'def': 'An NPN output/sensor that switches the negative (return) side and sinks current into the input card'},
  {'term': 'Sourcing', 'def': 'A PNP output/sensor that switches the positive side and sources current to the load or input card'},
  {'term': 'OTL/OTU', 'def': 'Output Latch / Unlatch instructions that set or clear a bit and hold it until explicitly changed'},
  {'term': 'TOF', 'def': 'Timer Off-Delay - keeps its output on for a preset time after the rung goes false'},
  {'term': 'RTO', 'def': 'Retentive Timer On-delay - accumulates time and retains it across power cycles until reset'},
  {'term': 'CTD', 'def': 'Count-Down counter - decrements on each false-to-true rung transition'},
  {'term': 'State Machine', 'def': 'A program structure where the machine is always in exactly one defined state with defined transitions - predictable and easy to troubleshoot'},
  {'term': 'ISA-101', 'def': 'The standard for high-performance HMI graphics: calm gray normal, color reserved for abnormal conditions'},
  {'term': 'ISA-18.2', 'def': 'The alarm-management standard that defines the alarm lifecycle and fights alarm floods through rationalization'},
  {'term': 'Alarm Flood', 'def': 'An overwhelming burst of alarms from a single event that hides the true root cause from the operator'},
  {'term': 'Tag', 'def': 'The named link between an HMI/SCADA object and a real value in a PLC'},
  {'term': 'OT', 'def': 'Operational Technology - the control-system networks and devices that run the process, valuing determinism and uptime'},
  {'term': 'Zones and Conduits', 'def': 'The IEC 62443 concept of grouping assets into security zones and tightly controlling the connections (conduits) between them'},
  {'term': 'Edge Computing', 'def': 'Processing data on or near the machine for fast local decisions and continued operation if the network drops'},
  {'term': 'Publish/Subscribe', 'def': 'The MQTT messaging model where devices publish to topics on a broker and clients subscribe to what they need, decoupling them'},
  {'term': 'Broker', 'def': 'The central MQTT server that receives published messages and routes them to subscribers'},
  {'term': 'TCP (robot)', 'def': "Tool Center Point - the working tip of the robot's tool, the reference for programmed points and linear moves"},
  {'term': 'Base Frame', 'def': "The fixed coordinate frame at the robot's mounting foot"},
  {'term': 'Singularity', 'def': 'A robot pose where the inverse-kinematics math breaks down and an axis would need near-infinite speed'},
  {'term': 'Cobot', 'def': 'Collaborative robot - designed with power-and-force limiting to work safely near people (ISO/TS 15066)'},
  {'term': 'Proportional (P)', 'def': 'The PID term that reacts to present error; fast but leaves a steady-state offset'},
  {'term': 'Integral (I)', 'def': 'The PID term that reacts to accumulated past error and eliminates steady-state offset'},
  {'term': 'Derivative (D)', 'def': 'The PID term that reacts to the rate of change of error, damping overshoot but amplifying noise'},
  {'term': 'Open-Loop', 'def': 'Control that commands an output with no measurement of the result (e.g. a fixed-time toaster)'},
  {'term': 'Closed-Loop', 'def': 'Feedback control that measures the result and self-corrects toward the setpoint'},
  {'term': 'Hierarchy of Controls', 'def': 'The risk-reduction order: eliminate/design-out, then engineering/guarding, then administrative, then PPE'},
  {'term': 'Voltage Drop Method', 'def': 'Measuring the small voltage across a connection under load to find high resistance an ohm test misses'},
  {'term': 'Live-Dead-Live', 'def': "Verifying a meter on a known source before and after testing, to trust that a 'dead' reading is real"},
  {'term': 'Availability', 'def': 'Uptime / (uptime + downtime) - combines reliability (MTBF) and repair speed (MTTR)'},
  {'term': 'Vibration Signature', 'def': 'The characteristic frequency of a fault: 1x imbalance, 1x/2x misalignment, harmonics looseness, high-freq bearings'},
  {'term': 'RCM', 'def': 'Reliability-Centered Maintenance - choosing the maintenance strategy per asset based on criticality and failure modes'},
  {'term': 'Commissioning', 'def': 'The disciplined bottom-up checkout (wiring, I/O, functions, integrated) that proves a system before production'},
  {'term': 'R_TRIG / F_TRIG', 'def': 'IEC 61131-3 edge-detection function blocks. R_TRIG.Q pulses TRUE for one scan on a rising CLK edge; F_TRIG on a falling edge - the Structured Text equivalent of a ladder one-shot.'},
  {'term': 'One-shot (ONS/OSR/OSF)', 'def': 'A ladder instruction that stays true for exactly one scan on a transition - ONS/OSR on rising, OSF on falling. Used to fire an action once per button press instead of every scan.'},
  {'term': 'Double-coil', 'def': 'A programming bug where the same output coil is written on more than one rung; because outputs update once per scan, only the last-solved rung controls the output, hiding intermittent behavior.'},
  {'term': 'IN_OUT parameter', 'def': "An AOI/function parameter passed by reference (not copied) so the block reads and writes the caller's live tag directly - efficient for large UDTs, unlike INPUT (copied in) and OUTPUT (copied out)."},
  {'term': 'Hysteresis (deadband)', 'def': 'Two separated switching thresholds that prevent output chatter - e.g. turn a fan ON at 80 deg and OFF at 70 deg; between the thresholds the output holds its last state.'},
  {'term': 'Watchdog timer', 'def': 'A processor supervisory timer that faults the controller if a single program scan takes too long - the reason unbounded loops in Structured Text are dangerous in scan-based code.'},
  {'term': 'Seal-in (latch)', 'def': "A three-wire control rung where the output's own contact is wired parallel to a momentary Start, keeping the output energized after Start is released until a series Stop breaks the path."},
  {'term': 'Time literal (T#)', 'def': "The IEC syntax for a duration constant in Structured Text - e.g. T#500ms, T#3s, T#1m30s, T#2h - passed to a timer's PT (preset time) input."},
]
