# -*- coding: utf-8 -*-
# Second hands-on exercise per module (more real-world / applied "field challenge").
# LABS2[module_id] = {"title":..,"tool":..,"steps":[..]}. build attaches m["lab2"].

LABS2 = {
 0: {"title":"Map Your Own Site","tool":"Paper/whiteboard + a walk of your area",
     "steps":["Pick one line or cell you work on (a sorter, a pick station, a robot cell)",
              "Walk it and list every sensor, motor, actuator, and controller you can find",
              "Sort each device onto the automation-pyramid level it belongs to",
              "Circle the one device whose failure would stop the most throughput - that is your critical asset"]},
 1: {"title":"Meter a Live Motor Starter (supervised)","tool":"DMM + a de-energized starter or trainer",
     "steps":["With power OFF and LOTO applied, identify L1/L2/L3, the contactor, OL, and control transformer",
              "Ring out (continuity) the control circuit from the Stop button through the M coil",
              "Predict the voltage you expect across the M coil when Start is pressed",
              "Energize (supervised), press Start, and confirm your predicted control voltage with the meter",
              "Trace and confirm the seal-in: release Start and verify the motor stays running"]},
 2: {"title":"Read a Live Rung Online","tool":"PLC software (Studio 5000, TIA, or a free sim like PLCfiddle)",
     "steps":["Open or build a simple start/stop rung with a seal-in",
              "Go online / run the sim and watch which contacts are highlighted (true)",
              "Toggle the Start input and watch the rung and output change scan-by-scan",
              "Force the Stop bit and explain out loud why the output drops",
              "Find one rung where the same bit is used on two rungs and predict last-state-wins"]},
 3: {"title":"Build a Bottle-Fill Sequence","tool":"PLC sim or pen/paper ladder",
     "steps":["Use a TON to hold a fill valve open for exactly 3 seconds after a bottle is detected",
              "Use a CTU to count 12 filled bottles, then set a 'case full' bit",
              "Add a reset that clears the counter when the case is removed",
              "Add a comparison so a 'low supply' input blocks the start",
              "Trace the sequence for 13 bottles and confirm the case-full logic fires correctly"]},
 4: {"title":"Scale and Verify a 4-20 mA Loop","tool":"DMM (mA) or loop calibrator + a transmitter",
     "steps":["Identify a 0-100 unit transmitter (pressure/level) and its analog card range",
              "Measure the loop current in mA and convert: %=(mA-4)/16",
              "Compute the engineering value and compare to the HMI/PLC reading",
              "Simulate a broken wire (open the loop) and confirm the reading goes to fault (0 mA / -25%)",
              "Write the scaling equation you would enter in the PLC for this loop"]},
 5: {"title":"Read a VFD Nameplate and Fault Log","tool":"A VFD (or its manual) + motor nameplate",
     "steps":["Record motor FLA, HP, base voltage, and base frequency from the nameplate",
              "Find those same parameters in the drive and confirm they match the motor",
              "Open the fault history and note the last 3 fault codes and when they occurred",
              "For each fault, classify it: did it trip on accel, decel, or steady state?",
              "Propose the most likely cause and one parameter or mechanical check for the top fault"]},
 6: {"title":"Troubleshoot a Dead Cylinder","tool":"Pneumatic trainer or a real air-actuated device (LOTO first)",
     "steps":["Confirm supply pressure at the FRL gauge and check the filter bowl for water/dirt",
              "Trace the schematic to identify the directional valve feeding the cylinder",
              "Meter the solenoid coil - is it getting its command voltage?",
              "If coil is powered but no motion, listen/feel for the spool shifting; suspect a stuck spool or lost air",
              "State whether your root cause is electrical (no signal) or mechanical (air/spool)"]},
 7: {"title":"Critique an HMI Screen","tool":"Any HMI screen at your site (photo it) + ISA-101 principles",
     "steps":["Photograph or sketch one operator screen you use",
              "Mark every place bright color is used - is each one truly an abnormal condition?",
              "Find a raw number that would be clearer as a trend or deviation bar",
              "Identify one element that adds clutter without adding information",
              "Redraw a 'high-performance' version: gray normal, color only for alarms"]},
 8: {"title":"Diagnose a Network Node","tool":"Laptop with ping + a managed switch (or its web page)",
     "steps":["Find a device's IP, subnet, and gateway; write them down",
              "Ping the device and a second device on the same subnet",
              "Open the switch and check the port's link status and error counters",
              "Simulate/consider a duplicate IP: predict what symptom two nodes would show",
              "Given an intermittent dropout, list the physical-layer checks you would do first"]},
 9: {"title":"Frame and Point Walk-Through","tool":"Robot teach pendant (or simulator / video)",
     "steps":["Identify the robot's base frame and its tool center point (TCP)",
              "Jog the robot in joint mode, then in linear (tool/world) mode - note the different paths",
              "Record two taught points and describe the move type between them",
              "Locate the E-stop, the enabling device, and the guarding for the cell",
              "Describe the LOTO/entry steps required before reaching into the envelope"]},
 10:{"title":"Watch a PID Loop Respond","tool":"A loop trend on the HMI/historian or a PID simulator",
     "steps":["Pick a real loop (temperature, level, flow, or speed) and note its SP and PV",
              "Make a small setpoint change and capture the response trend",
              "Classify the response: sluggish, good, or overshooting/oscillating?",
              "Decide which term you would adjust (P, I, or D) and in which direction",
              "Explain what physically happens if you double the integral gain"]},
 11:{"title":"Do a Mini Risk Assessment","tool":"A machine you maintain + the hierarchy of controls",
     "steps":["Pick one machine and list its top 3 hazards (crush, shear, electrical, etc.)",
              "For each, estimate severity, frequency of exposure, and avoidance",
              "Identify the current safeguard for each hazard and its type (fixed guard, interlock, sensing)",
              "Propose one higher-level control (eliminate/engineer) that would reduce a risk",
              "Verify: does any high-risk function rely on a single non-redundant switch?"]},
 12:{"title":"Trace One Fault Across Domains","tool":"A recent real down-event at your site + notes",
     "steps":["Pick a fault you (or a coworker) fixed recently",
              "Write the signal chain: sensor -> logic -> output -> mechanism, naming each device",
              "Mark which domain each link belongs to (electrical/controls/mechanical/network)",
              "Identify at which link the fault actually was and how it was confirmed",
              "Note what measurement would have found it fastest - build that into your habit"]},
 13:{"title":"Refactor Ladder into a State Machine","tool":"PLC sim or pen/paper (ST CASE)",
     "steps":["Take a sequence with several interlocked timers/latches (real or example)",
              "List the distinct states the machine can be in (Idle, Starting, Running, Faulted...)",
              "Define the transition condition between each pair of states",
              "Write it as a CASE statement in Structured Text (one branch per state)",
              "Explain why 'what state am I in and why won't I transition?' is easier to troubleshoot"]},
 14:{"title":"Sketch an IIoT Data Path","tool":"Paper + one connected asset at your site",
     "steps":["Pick a sensor whose data ends up on a dashboard or historian",
              "Draw where each processing step happens: edge, fog/gateway, cloud",
              "Decide which decisions must stay at the edge (latency/uptime) and why",
              "If it uses MQTT, name the broker and a likely topic; otherwise note the protocol",
              "List two OT-cybersecurity controls that should protect this path"]},
 15:{"title":"Live-Dead-Live and Voltage-Drop Hunt","tool":"DMM + a de-energized circuit (LOTO)",
     "steps":["Verify your meter on a known live source (live), then on the isolated circuit (dead), then live again",
              "With the circuit re-energized (supervised), find a suspect connection under load",
              "Measure voltage drop across that connection - more than a few tenths of a volt = high resistance",
              "Compare to a good connection nearby to set your baseline",
              "State whether a resistance test with power off would have caught this (usually not under load)"]},
 16:{"title":"Compute MTBF/MTTR for One Asset","tool":"CMMS/EAM work-order history + calculator",
     "steps":["Pull the last 6-12 months of failures for one asset from the CMMS",
              "Count failures and total downtime; compute MTBF and MTTR",
              "Compute availability = uptime/(uptime+downtime)",
              "Decide the right maintenance strategy for it (reactive/preventive/predictive) and why",
              "Name one condition-monitoring check that would move it toward predictive"]},
 17:{"title":"Panel Pre-Energize Checklist","tool":"A control panel (de-energized, LOTO) + the drawings",
     "steps":["With power OFF, verify 5 wires against the schematic wire numbers",
              "Check the ground/bond connections and tug-test terminal tightness",
              "Meter for shorts between L1-L2-L3 and to ground; confirm proper isolation",
              "Confirm main breaker/fuse rating and note the panel's SCCR label",
              "List the order you would bring it up: control power first, verify, then power circuits"]},
 18:{"title":"Draft Your Portfolio + 90-Day Plan","tool":"A document or notebook",
     "steps":["Write up one problem you solved: situation, what you did, measurable result",
              "List your current certs, equipment/brands you know, and tools you have built",
              "Pick ONE target skill and ONE target cert for the next quarter",
              "Name the concrete resources (course, manual, lab) and schedule the practice time",
              "Tie each goal to a real problem or asset at your site so it pays off immediately"]},
}
