"""AET Course module data — imported by build_course.py"""

MODULES = [
  {
    "id": 0, "title": "Introduction to Automation Engineering Technology",
    "objectives": ["Define AET and its role in modern manufacturing/logistics","Identify the 10 core technical domains of automation","Describe how automated systems integrate sensors, controllers, actuators, and networks","Map AET career paths and credentials (AAS, BSET, certs)"],
    "sections": [
      {"h": "What Is AET?", "body": "Automation Engineering Technology is the applied discipline of designing, installing, programming, operating, and maintaining automated industrial systems. It combines electrical/electronics, mechanical, computer-control, and systems-integration skills.<br><br>At Amazon fulfillment centers (like ACY1), AET skills are used daily by RME technicians maintaining conveyors, sorters, drives, PLCs, robotics cells, and safety systems."},
      {"h": "The Automation Pyramid", "body": "Industrial automation is modeled as a hierarchy:<br><b>Level 0</b> - Physical Process (motors, actuators, sensors)<br><b>Level 1</b> - Direct Control (PLCs, safety controllers)<br><b>Level 2</b> - Supervisory (HMI, SCADA)<br><b>Level 3</b> - Manufacturing Operations (MES, historians)<br><b>Level 4</b> - Enterprise (ERP, business systems)<br><br>AET technicians primarily work at Levels 0-2."},
      {"h": "The 10 Core Domains", "body": "<ol><li>Electrical Fundamentals & Motor-Control Wiring</li><li>PLCs (IEC 61131-3)</li><li>HMI / SCADA</li><li>Industrial Networks & Fieldbus</li><li>Motors, VFDs & Drives</li><li>Sensors & Instrumentation</li><li>Fluid Power (Pneumatics & Hydraulics)</li><li>Robotics & Motion Control</li><li>Process Control & PID</li><li>Machine Safety / Functional Safety</li></ol>"},
      {"h": "Career Paths", "body": "<b>Credentials:</b> AAS (2yr) - entry; Stackable certs (15-30 cr); BSET (4yr) - advanced.<br><b>Certifications:</b> ISA CCST, SACA C-101/C-201, FANUC Robot cert, Rockwell/Siemens vendor certs, NCCER Instrumentation.<br><b>At Amazon RME:</b> L4 Automation Engineer, Mechatronics & Robotics Technician, Senior AE (L5+)."}
    ],
    "lab": {"title": "Explore the Automation Pyramid", "tool": "Paper/whiteboard", "steps": ["Draw the 5-level automation pyramid","List 2-3 real devices from your site per level","Star areas where you want to grow"]},
    "quiz": [
      {"q": "What does AET stand for?", "options": ["Automated Electrical Testing","Automation Engineering Technology","Advanced Electronics Troubleshooting","Applied Energy Transmission"], "answer": 1, "explain": "AET = Automation Engineering Technology."},
      {"q": "At which levels do AET technicians primarily work?", "options": ["Levels 3-4","Levels 0-2 (Process/Control/Supervisory)","Level 4 only","Level 5 (Cloud)"], "answer": 1, "explain": "AET techs work at Levels 0-2."},
      {"q": "Most common 2-year AET entry credential?", "options": ["BSET","AAS (Associate of Applied Science)","MBA","PhD"], "answer": 1, "explain": "The AAS is the standard 2-year entry credential."}
    ],
    "resources": [{"name":"RealPars","url":"https://www.realpars.com/"},{"name":"ISA","url":"https://www.isa.org/"},{"name":"SACA","url":"https://www.saca.org/"}]
  },
  {
    "id": 1, "title": "Electrical Fundamentals & Motor-Control Wiring",
    "objectives": ["Apply Ohm's law and Kirchhoff's laws to DC circuits","Calculate RMS voltage/current in single/three-phase AC","Read industrial motor-control schematics (ladder diagrams)","Wire a 3-wire start/stop motor control circuit"],
    "sections": [
      {"h": "DC Fundamentals", "body": "<b>Ohm's Law:</b> V = I x R. <b>Power:</b> P = V x I.<br><b>KVL:</b> Voltage drops around a loop = 0. <b>KCL:</b> Currents in = currents out.<br><b>Series:</b> R_total = R1+R2+R3 (current same, voltage divides).<br><b>Parallel:</b> 1/R_total = 1/R1+1/R2 (voltage same, current divides).<br><i>Example:</i> 24V, R1=100, R2=200 series: I=80mA, V_R1=8V, V_R2=16V."},
      {"h": "AC Fundamentals", "body": "<b>RMS:</b> V_rms = V_peak / sqrt(2). 120V outlet = 170V peak.<br><b>Three-phase:</b> V_line = V_phase x sqrt(3). 480V/277V, 208V/120V.<br><b>Power factor:</b> PF = cos(theta). Motors = lagging PF < 1."},
      {"h": "Motor Control Circuits", "body": "<b>Power circuit:</b> L1/L2/L3 - disconnect - fuses - contactor(M) - OL - motor.<br><b>Control circuit:</b> 120V control transformer - Stop(NC) - Start(NO) - M coil - M aux(seal-in).<br><b>3-wire control:</b> Start momentarily energizes M; M aux seals in. Stop breaks seal. OL NC contact protects."},
      {"h": "Reading Schematics", "body": "Ladder diagrams: two vertical rails, horizontal rungs. Devices: M=starter, OL=overload, CR=relay, PB=pushbutton, LS=limit switch, SOL=solenoid, PL=pilot light."},
      {"h": "Electrical Safety &amp; Shock Hazards", "body": "Before any theory: electricity kills, and it does so at currents far smaller than most people expect. Know these numbers.<br><br><b>Current through the body (60 Hz AC, hand-to-hand):</b><br>&bull; ~1 mA - threshold of perception (tingle)<br>&bull; ~5 mA - the accepted safe upper limit; GFCIs trip around 5 mA<br>&bull; 10-20 mA - <b>let-go threshold</b> - muscles clamp and you cannot release the conductor<br>&bull; 50-150 mA - respiratory arrest, severe pain<br>&bull; 100-300 mA - <b>ventricular fibrillation</b> (the usual cause of electrocution death)<br><br>It is <b>current, not voltage,</b> that harms you - but voltage drives current through your body's resistance (dry skin ~100k ohm, wet/broken skin can drop below 1k ohm). At 120 V through 1k ohm that is 120 mA - lethal.<br><br><b>Arc flash</b> is a separate hazard: a fault can vaporize copper and release a blast of heat (35,000 &deg;F, hotter than the sun's surface), pressure, and molten metal. NFPA 70E governs the boundaries and PPE.<br><br><b>The controls: LOTO (Lockout/Tagout).</b> De-energize, isolate, lock, tag, and <b>verify zero energy with a meter you tested on a known source first</b> (test-before-touch / live-dead-live). Treat every conductor as energized until you personally prove otherwise. This single habit prevents most electrical fatalities."},
      {"h": "DC Circuits Worked in Depth", "body": "<b>Ohm's Law</b> ties the three quantities together: <b>V = I &times; R</b>. Rearrange as needed: I = V/R, R = V/I. <b>Power</b>: <b>P = V &times; I</b>, and by substitution <b>P = I&sup2;R = V&sup2;/R</b> (the I&sup2;R form is why undersized wire and loose connections overheat).<br><br><b>Series circuits</b> (one path): current is the <b>same</b> everywhere; voltages <b>add</b> and divide in proportion to resistance.<br><pre>R_total = R1 + R2 + R3 ...\n24 V, R1=100, R2=200 (series):\n  R_total = 300 ohm\n  I = 24 / 300 = 0.08 A (80 mA)\n  V_R1 = 0.08 * 100 = 8 V\n  V_R2 = 0.08 * 200 = 16 V   (8 + 16 = 24, checks)</pre><b>Parallel circuits</b> (multiple paths): voltage is the <b>same</b> across each branch; currents <b>add</b>.<br><pre>1/R_total = 1/R1 + 1/R2 ...\nTwo 100-ohm in parallel -&gt; 50 ohm\n(equal resistors: R / n)</pre><b>Kirchhoff's Laws</b> are the bookkeeping rules: <b>KVL</b> - the voltage rises and drops around any closed loop sum to zero. <b>KCL</b> - current into a node equals current out. Every troubleshooting measurement you make is really you applying KVL/KCL: a missing voltage drop means an open; an unexpected drop means added resistance (a bad connection).<br><br><b>Voltage divider:</b> two series resistors tap a fraction of the supply - <code>V_out = V_in &times; R2 / (R1 + R2)</code>. This is exactly how a potentiometer feedback or a resistive sensor reports position."},
      {"h": "AC Waveforms, RMS &amp; Measurement", "body": "AC (alternating current) reverses direction periodically, tracing a sine wave. Key descriptors:<br>&bull; <b>Frequency (f)</b> - cycles per second, in hertz. North America = 60 Hz, much of the world = 50 Hz.<br>&bull; <b>Period (T)</b> = 1/f. At 60 Hz, T = 16.67 ms.<br>&bull; <b>Peak</b> - the maximum instantaneous value; <b>peak-to-peak</b> = 2 &times; peak.<br><br><b>RMS (Root-Mean-Square)</b> is the value that matters. It is the equivalent DC value that would deliver the same heating power to a resistor. For a sine wave:<br><pre>V_rms = V_peak / sqrt(2) = 0.707 * V_peak\nV_peak = V_rms * sqrt(2) = 1.414 * V_rms\n\nA 120 V outlet is 120 V RMS -&gt; ~170 V peak\nA 480 V line is 480 V RMS -&gt; ~679 V peak</pre>When a nameplate or meter says '480 V AC,' it means RMS. This is why insulation must be rated for the higher peak.<br><br><b>True-RMS meters:</b> cheap averaging meters assume a clean sine and mis-read distorted waveforms - exactly what a VFD's chopped PWM output is. Always use a <b>true-RMS</b> meter on drive outputs and nonlinear loads, or your readings will be low.<br><br><b>Phase angle</b> describes how far two AC waveforms (or voltage vs current) are shifted from each other, measured in degrees of the 360&deg; cycle. In a purely resistive load, voltage and current are in phase; inductive loads (motors) make current lag - the root of power factor."},
      {"h": "Three-Phase Power Systems", "body": "Three-phase power is three AC voltages 120&deg; apart on the cycle. It is the backbone of industrial power because it delivers <b>constant, smooth power</b> (the three phases fill each other's gaps) and lets motors self-start with a rotating field.<br><br><b>Two ways to connect three phases:</b><br>&bull; <b>Wye (Y / star):</b> three windings share a common <b>neutral</b> point. Gives you two voltages: line-to-line and line-to-neutral.<br>&bull; <b>Delta:</b> windings form a closed triangle, no neutral. Line and phase voltage are equal.<br><br><b>The sqrt(3) relationship (Wye):</b><br><pre>V_line = V_phase * sqrt(3)   (sqrt(3) = 1.732)\n\n480 V line  / 277 V to neutral   (480 = 277 * 1.732)\n208 V line  / 120 V to neutral   (208 = 120 * 1.732)</pre>That is why a 480 V facility gives 277 V for lighting and a 208 V system gives the familiar 120 V receptacles - all from the same transformer.<br><br><b>Line vs phase current:</b> in a wye load line current = phase current; in a delta load <code>I_line = I_phase &times; sqrt(3)</code>. <br><br><b>Three-phase power:</b> <code>P = sqrt(3) &times; V_line &times; I_line &times; PF</code>. Memorize this - it sizes conductors, breakers, and drives for every motor in the building.<br><br><b>Phase rotation (A-B-C vs A-C-B)</b> sets motor direction. Swap any two of the three leads and a motor reverses - the single most common field fix for a backwards conveyor."},
      {"h": "Power, Energy &amp; Power Factor", "body": "Three kinds of power live in every AC system with motors:<br>&bull; <b>Real power (P)</b>, in <b>kW</b> - actual work done (turning the shaft, making heat/light).<br>&bull; <b>Reactive power (Q)</b>, in <b>kVAR</b> - power that sloshes back and forth building the magnetic fields in motor/transformer windings; does no net work.<br>&bull; <b>Apparent power (S)</b>, in <b>kVA</b> - the vector sum the utility must actually supply.<br><br><b>The power triangle:</b><br><pre>     S (kVA)\n      /|\n     / | Q (kVAR)\n    /  |\n   /___|\n    P (kW)\n\nS = sqrt(P^2 + Q^2)</pre><b>Power factor (PF)</b> = P / S = cos(theta), a number from 0 to 1. A PF of 1.0 means all supplied power does work. Motors are <b>inductive</b>, so their current <b>lags</b> voltage and PF is less than 1 (typically 0.8-0.9 at full load, worse when lightly loaded).<br><br><b>Why it matters:</b> a low PF means the utility ships extra current for the same real work - bigger conductors, more losses, and <b>PF penalty charges</b> on the bill. <b>PF correction</b> (capacitor banks) supplies the reactive power locally and pulls PF back toward 1.<br><br><b>Energy</b> is power &times; time - the <b>kWh</b> the meter bills. A 10 kW load running a full shift (8 h) uses 80 kWh."},
      {"h": "Conductors, Ampacity &amp; Voltage Drop", "body": "A conductor is sized by two independent limits - <b>ampacity</b> (can it carry the current without overheating?) and <b>voltage drop</b> (does enough voltage reach the load?).<br><br><b>Wire gauge (AWG):</b> counterintuitively, a <b>bigger number = smaller wire</b>. 14 AWG is small (branch lighting), 12 and 10 AWG for receptacles/small motors, and the number drops (4, 2, 1/0, 2/0...) as wire gets fatter for feeders.<br><br><b>Ampacity</b> is the safe continuous current for a conductor, set by insulation temperature rating (60/75/90 &deg;C columns in NEC Table 310.16) and <b>derated</b> for high ambient temperature and for bundling many current-carrying conductors in one raceway. Common insulation: <b>THHN/THWN</b> (the workhorse), rated 90 &deg;C dry.<br><br><b>Voltage drop</b> - long runs waste voltage in the wire's own resistance:<br><pre>Vdrop = I * R_wire\n3-phase: Vdrop = 1.732 * I * R_per_ft * length_ft\n\nRule of thumb: keep total drop under 3% for\nbranch circuits, 5% feeder-plus-branch.</pre>An under-volted motor draws <b>more</b> current to make the same torque, running hot and tripping overloads - a classic 'long run to the far conveyor' problem. The fix is up-sizing the conductor, not the overload setting.<br><br><b>Terminations</b> matter as much as wire: a loose or corroded lug adds resistance, drops voltage, and generates I&sup2;R heat - the leading cause of panel hot-spots found on thermographic scans."},
      {"h": "Grounding &amp; Bonding", "body": "<b>Grounding</b> and <b>bonding</b> are related but not the same, and technicians who conflate them make dangerous mistakes.<br><br>&bull; <b>Grounding</b> = deliberately connecting a system point to earth via a grounding electrode (ground rod, Ufer, water pipe). It sets a reference potential and gives lightning/surges a path.<br>&bull; <b>Bonding</b> = electrically joining all normally-non-current-carrying metal parts (enclosures, raceways, motor frames) together with the <b>equipment grounding conductor (EGC)</b> so they are all at the same potential.<br><br><b>Why bond?</b> If a hot conductor faults to a motor frame, the EGC provides a low-impedance path back to the source so overcurrent protection clears the fault <b>fast</b>. Without a solid bond, the frame just floats at line voltage waiting for a human body to complete the circuit.<br><br><b>Neutral vs ground:</b> the <b>neutral</b> is a current-carrying conductor - the return leg of a wye system. The <b>ground/EGC</b> should carry <b>zero current</b> in normal operation. They are bonded together at <b>exactly one point</b> - the service disconnect. Bonding neutral to ground anywhere downstream creates a parallel current path that circulates current on grounding conductors, disrupts sensitive electronics, and defeats GFCIs.<br><br><b>GFCI (Ground-Fault Circuit Interrupter):</b> measures the difference between hot and neutral current. Any imbalance means current is leaving the circuit through something else (a human?). Trips at ~5 mA in ~25 ms - fast enough to prevent electrocution. Required on wet/outdoor circuits.<br><br><b>Ground faults</b> and <b>short circuits</b> differ: a short is hot-to-neutral (high current, breaker trips on overcurrent); a ground fault is hot-to-ground (may be lower current, trips on GFCI/GFPE). Motor drives often have their own <b>ground-fault protection (GFPE)</b> tuned for the load."},
      {"h": "Transformers", "body": "A transformer is two (or more) magnetically-coupled coils on a common iron core. AC in the primary sets up a changing magnetic flux; that flux induces AC voltage in the secondary. There is no direct electrical connection between primary and secondary - that isolation is often the point.<br><br><b>Turns ratio</b> sets the voltage ratio:<br><pre>V_p / V_s = N_p / N_s = I_s / I_p\n\nStep DOWN 480 V -&gt; 120 V: 4:1 turns\nCurrent steps UP by 4:1 on the secondary.</pre>Power in equals power out (minus small losses): a step-down transformer trades voltage for current. That is why the low-voltage secondary conductor is <b>fatter</b>, not smaller.<br><br><b>Ratings you will see:</b><br>&bull; <b>VA / kVA</b> - apparent power capacity (a 500 VA control transformer at 120 V can supply ~4.2 A).<br>&bull; <b>Primary / secondary voltage</b> - often with taps (2.5% above/below nominal) to fine-tune for high or low incoming line.<br>&bull; <b>Impedance %Z</b> - how much voltage sags at full load; also sets the available short-circuit current at the secondary.<br><br><b>Common industrial types:</b><br>&bull; <b>Control transformer (CPT):</b> small, drops line voltage (typically 480 V) to a 120 V or 24 V control circuit. Almost every motor-control panel has one.<br>&bull; <b>Isolation transformer:</b> 1:1 ratio, used to break a ground reference between two systems and reduce common-mode noise on sensitive electronics.<br>&bull; <b>Distribution / dry-type:</b> the 480/208-120 units mounted throughout a facility to feed panels.<br><br><b>Inrush</b> - transformers can draw 8-15&times; rated current for a few cycles when first energized as the core magnetizes. Size upstream breakers/fuses to ride through this, or you will nuisance-trip every time the panel is powered up."},
      {"h": "Motor-Control Components in Depth", "body": "A typical across-the-line motor starter contains six standardized parts. Know each by touch:<br><br><b>1. Disconnect switch</b> - the visible break that isolates the panel from line power for maintenance. Fused disconnects add short-circuit protection.<br><br><b>2. Overcurrent protection</b> - <b>fuses</b> or <b>circuit breakers</b> upstream of the contactor. Sized for <b>short-circuit</b> and <b>ground-fault</b> protection only - they are NOT the overload for the motor.<br>&bull; <b>Fuses:</b> one-time devices, very fast, high AIC ratings; class J/CC are common in modern panels.<br>&bull; <b>Breakers / MCP (motor circuit protector):</b> resettable, magnetic-only for motor branch circuits.<br><br><b>3. Contactor</b> - an electromagnetically-operated switch. A control-voltage coil pulls in the armature, closing three heavy power contacts (L1/L2/L3 -&gt; T1/T2/T3) plus auxiliary contacts for control-circuit sealing/signaling. NEMA sizes 00-9 or IEC current ratings.<br><br><b>4. Overload relay (OL)</b> - the actual motor protection. Reads motor current and trips a <b>normally-closed contact</b> in the control circuit if the motor is overloaded. <b>Class 10 / 20 / 30</b> = seconds to trip at 600% FLA. Class 10 for hermetic/submersible, <b>Class 20 is the common default</b>, Class 30 for high-inertia loads. Solid-state (electronic) OLs add phase-loss and unbalance detection.<br><br><b>5. Control transformer + fuse</b> - drops line to control voltage (typically 120 VAC or 24 VDC), fused on both primary and secondary per NEC 450.<br><br><b>6. Pilot devices</b> - Start (NO momentary), Stop (NC momentary), pilot lights (Run/Ready/Fault), selector switches (HOA = Hand/Off/Auto), E-stop mushroom (NC held closed by twist-release).<br><br><b>The whole starter</b> = disconnect &rarr; fuses/breaker &rarr; contactor &rarr; OL &rarr; motor, with the control-circuit coil energized through Start/Stop/OL-aux/interlocks. Every industrial motor circuit in the plant follows this same skeleton."},
      {"h": "Control-Circuit Logic - 2-Wire, 3-Wire, Reversing &amp; Interlocks", "body": "<b>2-wire control</b> - a single maintained device (thermostat, float switch, PLC output) directly energizes the coil. When the device is closed the motor runs; when open it stops. <b>Restarts automatically on power return</b> - fine for a pump on a float, dangerous for a conveyor an operator loaded by hand.<br><br><b>3-wire control</b> - the safety-standard motor circuit:<br><pre>L1 --[Stop NC]--+--[Start NO]--+-- M coil -- L2\n                |               |\n                +----[M aux]----+   (seal-in)</pre>Pressing <b>Start</b> momentarily energizes coil M; M's own auxiliary contact closes to seal itself in around Start. <b>Stop</b> or an overload opens the loop and drops the coil. Because the coil requires a deliberate Start press, power loss = motor off; power return does NOT auto-restart. This is why every hand-operated machine uses 3-wire.<br><br><b>Reversing starter</b> - two contactors (F and R) tied together mechanically and electrically:<br>&bull; <b>Mechanical interlock</b> - a physical seesaw that prevents both from pulling in at once (that would short two phases).<br>&bull; <b>Electrical interlock</b> - each contactor's NC auxiliary is wired in series with the OTHER coil. F cannot pick up while R is in, and vice versa.<br>&bull; F swaps two of the three power leads via its contacts, reversing phase rotation and thus motor direction.<br><br><b>Jogging</b> - Jog pushbutton bypasses the seal-in so the motor runs only while the button is held (setup/positioning without full run).<br><br><b>HOA (Hand/Off/Auto)</b> selector - Hand = direct manual run; Auto = PLC/control input runs it; Off breaks both. A cornerstone of every conveyor and pump panel.<br><br><b>Interlocks</b> broadly = safety or process conditions wired in series with the coil so the motor cannot run unless permissions are true (guard closed, upstream conveyor ready, oil pressure OK, no E-stop). Add interlocks to the <b>control</b> circuit, never bypass the safety chain to 'get running.'"},
      {"h": "Reading Electrical Prints", "body": "Industrial documentation comes in several coordinated views - each answers a different question. Read them together, not in isolation.<br><br><b>1. Ladder / elementary diagram</b> - the LOGIC. Two vertical rails (L1/L2), rungs with input devices on the left and coils/lamps on the right. Reads top-to-bottom. Wire numbers on both ends of each conductor. This tells you WHAT the circuit does.<br><br><b>2. Schematic (one-line / three-line)</b> - the POWER path. Shows main breakers, feeders, transformers, drives, and motors. The single-line uses one symbol per three-phase element; the three-line breaks it out phase-by-phase for troubleshooting.<br><br><b>3. Wiring / connection diagram</b> - the physical PHYSICAL layout: which terminal on which device connects to which wire number. This tells you HOW to actually land the wire.<br><br><b>4. Panel layout drawing</b> - the mechanical arrangement of components on the subplate, plus dimensions for door cutouts and mounting holes.<br><br><b>Wire numbering</b> is the connective tissue: every wire carries a unique number that appears on the same tag at every termination and on every diagram. If you find wire <b>101</b> on the ladder and cannot find <b>101</b> in the panel, the drawing is out of date - update it.<br><br><b>Symbols - NEMA vs IEC:</b><br>&bull; <b>NEMA</b> uses named devices with letter designators - M (motor starter), CR (control relay), OL (overload), TR (timer), PB (pushbutton), LS (limit switch), SOL (solenoid), PL (pilot light). Contacts show N.O. as two facing lines, N.C. with a diagonal slash.<br>&bull; <b>IEC</b> uses numeric designations (K for contactors/relays, F for fuses, Q for breakers/disconnects) and circle-based contact symbols. More common on European equipment.<br><br><b>Cross-references</b> - a coil like <code>CR-14</code> at rung 14 has its contacts scattered on other rungs. Good prints list the rung numbers where each contact lives right next to the coil symbol, so you can jump instantly."},
      {"h": "Test Instruments &amp; Safe Measurement", "body": "A technician is only as good as the meter in their hand and the discipline behind using it.<br><br><b>Digital Multimeter (DMM)</b> - your daily driver. Modes:<br>&bull; <b>VAC / VDC</b> - measure across two points, meter in parallel with the load.<br>&bull; <b>A (Amps)</b> - measure current, meter in <b>series</b>. Ammeter in parallel = short circuit = blown fuse or worse. Use a clamp meter instead for high current.<br>&bull; <b>Ohms</b> - <b>DE-ENERGIZE FIRST</b>. Applying an ohmmeter to a live circuit can damage the meter or feed backward through the circuit.<br>&bull; <b>Continuity</b> - audible beep for &lt; ~30 ohm. Fast fuse/wire checks.<br>&bull; <b>Diode</b> - forward drop; also identifies polarity of LEDs.<br>&bull; <b>Frequency, capacitance, temperature</b> - useful accessories.<br><br><b>Clamp meter</b> - measures AC (and often DC) current by sensing the magnetic field around a single conductor without breaking the circuit. Clamp ONE conductor (line OR neutral, not both - clamping both cancels out and reads zero, though that IS how you detect a ground fault on a feeder).<br><br><b>Megohmmeter (Megger)</b> - applies 250/500/1000 VDC and reads insulation resistance in megohms. Used to prove motor windings, cable insulation, and control transformers are still good. Rule of thumb: at least 1 megohm per kV of rated voltage plus 1 - a 480 V motor should read at least 1.5 M-ohm cold. <b>Never megger a device with electronics installed</b> - the high test voltage will destroy VFDs and drives.<br><br><b>CAT ratings</b> - the meter's category rating tells you where it can be used safely:<br>&bull; <b>CAT II</b> - single-phase receptacle-level equipment<br>&bull; <b>CAT III</b> - three-phase distribution and motor loads (most industrial work)<br>&bull; <b>CAT IV</b> - service entrance and outdoor drops<br>Using a CAT II meter on a CAT III bus is how meters explode. Match the meter to the environment, wear rated PPE, and always perform the <b>test-before-touch / live-dead-live</b> verification against a known source."}
    ],
    "lab": {"title": "Start/Stop Circuit", "tool": "PLCfiddle or pen/paper", "steps": ["Draw 3-wire start/stop with Stop(NC), Start(NO), M coil, M aux, OL(NC)","Trace current when Start pressed","Trace when Stop pressed","Add a pilot light for 'running'"]},
    "quiz": [
      {"q": "480V 3-phase: what is phase voltage?", "options": ["480V","277V","208V","120V"], "answer": 1, "explain": "V_phase = 480/sqrt(3) = 277V."},
      {"q": "What seals in the motor coil after releasing Start?", "options": ["Overload relay","M auxiliary contact (parallel with Start)","Disconnect","Gravity"], "answer": 1, "explain": "M aux contact seals in the coil."},
      {"q": "What does NC overload contact do?", "options": ["Starts motor","Speed control","Opens to de-energize coil on overload","Adds braking"], "answer": 2, "explain": "OL NC opens on overload, breaking coil circuit."},
      {"q": "Approximately what body current is the 'let-go threshold' (muscles clamp, you cannot release)?", "options": ["1 mA", "10-20 mA", "100 mA", "1 A"], "answer": 1, "explain": "5 mA is the safe limit and roughly perception; 10-20 mA causes involuntary muscle contraction so you cannot let go. 100+ mA causes ventricular fibrillation."},
      {"q": "What must you do BEFORE trusting that a circuit is de-energized during LOTO?", "options": ["Look at the meter for a moment", "Assume the disconnect is off", "Test-before-touch on a KNOWN LIVE source first, then verify the target is dead, then re-verify meter on known live", "Wait 30 seconds"], "answer": 2, "explain": "Live-Dead-Live: prove the meter works on a known energized source, verify the target reads zero, then re-verify the meter still works. Catches a broken meter or a bad lead."},
      {"q": "A 480 V RMS three-phase line has what approximate peak voltage?", "options": ["339 V", "480 V", "679 V", "960 V"], "answer": 2, "explain": "V_peak = V_rms * sqrt(2) = 480 * 1.414 = ~679 V. This peak is what insulation must withstand."},
      {"q": "On a 480 V wye system, what is the line-to-neutral voltage?", "options": ["120 V", "208 V", "277 V", "480 V"], "answer": 2, "explain": "V_line = V_phase * sqrt(3). 480 / 1.732 = ~277 V line-to-neutral - the voltage that feeds industrial lighting."},
      {"q": "Motors are inductive loads. How does power factor typically behave at full load?", "options": ["PF is exactly 1.0", "Current LEADS voltage; PF is capacitive", "Current LAGS voltage; PF is ~0.8-0.9 lagging", "PF does not apply to motors"], "answer": 2, "explain": "Motor windings store energy in magnetic fields, so current lags voltage. Typical full-load PF is 0.8-0.9; correction capacitors bring it toward 1."},
      {"q": "For AWG (American Wire Gauge), which statement is correct?", "options": ["Bigger AWG number = bigger wire", "Bigger AWG number = smaller wire (12 is smaller than 10)", "AWG numbers do not indicate size", "AWG only applies to aluminum"], "answer": 1, "explain": "Counterintuitive but standard: as AWG number grows, wire cross-section shrinks. Beyond 1 AWG we go to 1/0, 2/0, 3/0, 4/0 (bigger)."},
      {"q": "The equipment grounding conductor (EGC) should normally carry:", "options": ["The same current as the neutral", "Half the load current", "Zero current under normal operation", "Only DC current"], "answer": 2, "explain": "The EGC bonds metallic parts together and is a fault-return path only. Any steady current on the EGC means a wiring error or a fault."},
      {"q": "Where is the neutral bonded to ground in a typical facility service?", "options": ["At every subpanel", "At each motor", "At exactly one point - the service disconnect / main bonding jumper", "Wherever convenient"], "answer": 2, "explain": "Neutral and ground are bonded at exactly one point (the service). Bonding downstream creates parallel current paths on grounding conductors and defeats GFCI protection."},
      {"q": "A step-down transformer changes 480 V primary to 120 V secondary. What happens to the current?", "options": ["Steps down by the same 4:1 ratio", "Stays the same", "Steps UP by ~4:1 (power in = power out, so lower voltage = higher current)", "Doubles"], "answer": 2, "explain": "Turns ratio 4:1 down for voltage means 1:4 up for current. Same real power in and out (minus small losses); that is why secondary conductors are heavier."},
      {"q": "Which class of overload relay is the common default for general-purpose motor protection?", "options": ["Class 5", "Class 10", "Class 20", "Class 30"], "answer": 2, "explain": "Class 20 = trip in ~20 s at 600% FLA - the workhorse. Class 10 for hermetic/submersible (fast trip), Class 30 for high-inertia loads."},
      {"q": "The signature feature of 3-wire (versus 2-wire) motor control is:", "options": ["It uses three phases", "It has three pushbuttons", "Momentary Start + seal-in + Stop - power loss requires a deliberate Start press to restart, no auto-restart", "It uses three overloads"], "answer": 2, "explain": "3-wire control uses a momentary Start with a seal-in auxiliary; loss of coil power drops the seal, so it does not auto-restart when power returns. 2-wire auto-restarts."},
      {"q": "Why must you NEVER megger (apply 500-1000 VDC insulation test) to a VFD or drive?", "options": ["It takes too long", "The DC voltage will destroy the drive's internal electronics", "It always gives a false reading", "It only works on 60 Hz"], "answer": 1, "explain": "A megger's high DC test voltage far exceeds the ratings of the drive's semiconductors. Disconnect the drive from the motor leads before meggering the motor."}
    ],
    "resources": [{"name":"All About Circuits - DC","url":"https://www.allaboutcircuits.com/textbook/direct-current/"},{"name":"All About Circuits - AC","url":"https://www.allaboutcircuits.com/textbook/alternating-current/"},{"name":"Khan Academy EE","url":"https://www.khanacademy.org/science/electrical-engineering"}]
  },
  {
    "id": 2, "title": "PLC Fundamentals",
    "objectives": ["Explain the PLC scan cycle","Identify I/O types (discrete/analog, sinking/sourcing)","Write basic ladder logic: XIC, XIO, OTE, OTL, OTU","Describe IEC 61131-3 languages (LD, FBD, ST, SFC)"],
    "sections": [
      {"h": "What Is a PLC?", "body": "A <b>Programmable Logic Controller</b> reads inputs, executes a user program, and controls outputs in real time. Components: CPU, Power Supply, I/O Modules, Comm ports. Replaces hardwired relay logic with software."},
      {"h": "The Scan Cycle", "body": "Every PLC repeats: <ol><li><b>Input Scan</b> - read all inputs to image table</li><li><b>Program Scan</b> - execute logic top-to-bottom using input image</li><li><b>Output Scan</b> - write output image to physical outputs</li><li><b>Housekeeping</b> - comms, diagnostics, watchdog</li></ol>Typical scan: 5-50ms."},
      {"h": "Addressing", "body": "<b>Allen-Bradley Logix:</b> Tag-based names.<br><b>Siemens S7:</b> I0.0, Q0.0, M0.0, DB1.DBX0.0.<br><b>Legacy AB SLC:</b> I:1/0, O:0/0, B3:0/0.<br><b>Discrete:</b> 24VDC; NPN(sinking) vs PNP(sourcing).<br><b>Analog:</b> 4-20mA or 0-10V, 12-16 bit."},
      {"h": "Basic Ladder Instructions", "body": "<b>XIC</b> (Examine Closed) - TRUE when bit=1<br><b>XIO</b> (Examine Open) - TRUE when bit=0<br><b>OTE</b> (Output Energize) - ON when rung true<br><b>OTL/OTU</b> - Latch/Unlatch (retentive)<br><b>Branches</b> - parallel=OR, series=AND"},
      {"h": "IEC 61131-3 Languages", "body": "<b>LD</b> - Ladder (graphical, relay-style)<br><b>FBD</b> - Function Block (graphical blocks)<br><b>ST</b> - Structured Text (Pascal-like)<br><b>SFC</b> - Sequential Function Chart (state machine)<br>Most programs MIX: LD for discrete, ST for math, SFC for sequences."}
    ],
    "lab": {"title": "Build Start/Stop in Ladder", "tool": "OpenPLC Editor (free)", "steps": ["Create BOOL vars: Start_PB, Stop_PB, Motor_Run, Seal","Write ladder: (Start OR Seal) AND NOT Stop -> Seal; Seal -> Motor_Run","Simulate and verify","Add TON timer: 5s delay before Conveyor_Ready energizes"]},
    "quiz": [
      {"q": "When does the PLC read physical inputs?", "options": ["Program scan","Output scan","Input scan (beginning)","Housekeeping"], "answer": 2, "explain": "Inputs read at start of each scan."},
      {"q": "XIO is TRUE when bit is:", "options": ["1 (ON)","0 (OFF)","Floating","Pulsing"], "answer": 1, "explain": "XIO = TRUE when bit is 0 (OFF)."},
      {"q": "Which IEC 61131-3 language is text-based like Pascal?", "options": ["Ladder","FBD","Structured Text","SFC"], "answer": 2, "explain": "Structured Text is the text-based language."}
    ],
    "resources": [{"name":"OpenPLC Project","url":"https://openplcproject.com/"},{"name":"PLCfiddle","url":"https://plcfiddle.com/"},{"name":"RealPars - PLC Basics","url":"https://www.realpars.com/"}]
  },
  {
    "id": 3, "title": "PLC Programming II - Timers, Counters & Data",
    "objectives": ["Program TON, TOF, RTO timers","Program CTU/CTD counters","Use comparison and math instructions","Organize programs with subroutines/tasks"],
    "sections": [
      {"h": "Timers", "body": "<b>TON:</b> Accumulates while input TRUE; DN sets when ACC>=PRE; resets when input FALSE.<br><b>TOF:</b> DN ON immediately; counts after input FALSE; DN drops when ACC>=PRE.<br><b>RTO:</b> Like TON but retentive - needs explicit RES to clear.<br>Time base: PRE in ms (AB) or TIME type (Siemens T#5s)."},
      {"h": "Counters", "body": "<b>CTU:</b> Increments on false-to-true transition. DN when ACC>=PRE.<br><b>CTD:</b> Decrements. DN when ACC<=0.<br>Applications: batch counting, part counting, shift production tracking."},
      {"h": "Comparison & Math", "body": "<b>Compare:</b> EQU, NEQ, GRT, GEQ, LES, LEQ.<br><b>Math:</b> ADD, SUB, MUL, DIV, MOD, SQR.<br><b>Move:</b> MOV, COP, FLL.<br><i>Scaling example:</i> PSI = ((Raw - 6553) x 100) / 26214."},
      {"h": "Program Organization", "body": "<b>AB Logix:</b> MainTask/MainRoutine calls subroutines via JSR. Separate routines for Inputs, Sequence, Outputs, Alarms, HMI.<br><b>Tasks:</b> Continuous, Periodic (fixed interval), Event (triggered).<br><b>Siemens:</b> OB1, FCs, FBs with instance DBs, global DBs."}
    ],
    "lab": {"title": "Traffic Light Sequencer", "tool": "OpenPLC or CODESYS (free)", "steps": ["Create outputs: Red, Yellow, Green","Use 3 TON timers: Green=10s, Yellow=3s, Red=10s","Build sequence cycling through all states","Add CTU counting cycles; at 10 set Maintenance_Due","Add RES on Reset_PB"]},
    "quiz": [
      {"q": "TON PRE=3000ms, input TRUE for 2s then FALSE. Final ACC?", "options": ["3000","2000","0","5000"], "answer": 2, "explain": "TON resets ACC to 0 when input goes FALSE."},
      {"q": "Which timer retains ACC when input drops?", "options": ["TON","TOF","RTO","CTU"], "answer": 2, "explain": "RTO is retentive - keeps ACC, needs separate RES."},
      {"q": "Scale raw 6553-32767 to 0-100:", "options": ["EU = Raw x 100","EU = ((Raw-6553) x 100) / 26214","EU = Raw / 327.67","EU = Raw - 6553"], "answer": 1, "explain": "Subtract offset, multiply by EU span, divide by raw span."}
    ],
    "resources": [{"name":"RealPars - Timers","url":"https://www.realpars.com/"},{"name":"CODESYS","url":"https://www.codesys.com/"},{"name":"The Automation Blog","url":"https://theautomationblog.com/"}]
  },
  {
    "id": 4, "title": "Sensors & Instrumentation",
    "objectives": ["Select sensor types for various measurement needs","Wire NPN/PNP sensors to PLC inputs","Interpret 4-20 mA signals and scale to engineering units","Configure encoder feedback"],
    "sections": [
      {"h": "Discrete Sensors", "body": "<b>Inductive:</b> Metal only, 2-30mm range.<br><b>Capacitive:</b> Any material, shorter range.<br><b>Photoelectric:</b> Through-beam (longest range), Retroreflective, Diffuse (shortest).<br><b>Ultrasonic:</b> Any material, distance measurement.<br><b>NPN vs PNP:</b> NPN=sinking (switch to 0V), PNP=sourcing (switch to +V). Match to PLC input type."},
      {"h": "Analog Instruments", "body": "<b>4-20 mA:</b> 4mA=zero (live zero - 0mA = wire break fault). Immune to wire resistance.<br><b>Temperature:</b> RTD (Pt100, accurate), Thermocouple (J/K/T, wide range), Thermistor.<br><b>Pressure:</b> Gauge/absolute/differential, diaphragm/strain gauge.<br><b>Flow:</b> Magnetic, Coriolis, Vortex, DP.<br><b>Level:</b> Ultrasonic, Radar, Capacitance, Float."},
      {"h": "Encoders", "body": "<b>Incremental:</b> A/B (quadrature for direction), Z (index). Effective counts = PPR x 4.<br><b>Absolute:</b> Unique position code, no homing needed. SSI, BiSS output.<br>Applications: conveyor tracking, motor speed (RPM = pulses/time x 60/PPR)."},
      {"h": "Scaling & Calibration", "body": "EU = ((Raw - Raw_Low) / (Raw_High - Raw_Low)) x (EU_High - EU_Low) + EU_Low<br><b>Calibration:</b> Apply known reference, verify mA output, adjust zero (4mA) and span (20mA)."}
    ],
    "lab": {"title": "Sensor Wiring & Scaling", "tool": "Pen/paper + calculator", "steps": ["Draw PNP sensor wiring to 24VDC sinking PLC input","Draw 2-wire 4-20mA transmitter to analog input","Calculate: raw 19660 (range 6553-32767), 0-100 PSI = ? (Answer: 50 PSI)","Encoder 1024 PPR with x4 decoding = ? counts/rev (4096)"]},
    "quiz": [
      {"q": "4-20 mA reads 0 mA. What does this mean?", "options": ["Zero process value","Full scale","Wire break / transmitter failure","Normal at 0%"], "answer": 2, "explain": "4mA = live zero. 0mA = broken loop."},
      {"q": "PNP sensor switches which voltage when active?", "options": ["+V (supply)","0V (ground)","AC line","4-20 mA"], "answer": 0, "explain": "PNP = sourcing = connects output to +V."},
      {"q": "500 PPR encoder with x4 decoding:", "options": ["500","1000","2000","4000"], "answer": 2, "explain": "500 x 4 = 2000 counts/rev."}
    ],
    "resources": [{"name":"Inst Tools","url":"https://instrumentationtools.com/"},{"name":"AutomationDirect","url":"https://www.automationdirect.com/"},{"name":"RealPars - Sensors","url":"https://www.realpars.com/"}]
  },
  {
    "id": 5, "title": "Motors, VFDs & Drives",
    "objectives": ["Read motor nameplates (HP, FLA, RPM, SF, insulation, frame)","Explain VFD operation (rectifier-DC bus-inverter, V/Hz)","Configure essential VFD parameters","Diagnose common VFD faults (OC, OV, UV, OL, GF, OH)"],
    "sections": [
      {"h": "AC Induction Motors", "body": "Stator creates rotating field; rotor dragged by induction (always slower = slip).<br><b>Sync speed:</b> n = 120 x f / P. 60Hz 4-pole = 1800RPM sync, ~1750 actual.<br><b>Nameplate:</b> HP, FLA, RPM, Voltage, SF (1.15 typ), Insulation (F=155C), NEMA frame, Enclosure (TEFC/ODP)."},
      {"h": "VFD Principles", "body": "<b>Sections:</b> Rectifier (AC-DC, 6-pulse diode) - DC Bus (capacitors, ~650VDC for 480V) - Inverter (IGBT switching, variable V and f).<br><b>V/Hz:</b> Constant ratio maintains flux/torque. 460V/60Hz = 7.67V/Hz. At 30Hz output ~230V.<br><b>Vector control:</b> Independently controls flux and torque for better dynamics."},
      {"h": "Key Parameters", "body": "Motor data (V, FLA, HP, RPM, Hz). Accel/Decel time. Current limit (150% 60s, 200% 3s). Control mode (V/Hz, Sensorless Vector, Closed-loop Vector). Braking (coast, DC injection, dynamic braking resistor, regen)."},
      {"h": "Common Faults", "body": "<b>OC:</b> Overcurrent - short/ground/jam/fast accel.<br><b>OV:</b> Overvoltage - fast decel/regen/supply spike.<br><b>UV:</b> Undervoltage - power sag/blown phase fuse.<br><b>OL:</b> Overload (I2t) - sustained overload/poor ventilation.<br><b>GF:</b> Ground fault - damaged insulation/wet motor.<br><b>OH:</b> Overtemp - blocked fan/high ambient/carrier freq too high."}
    ],
    "lab": {"title": "VFD Parameter Worksheet", "tool": "Any VFD manual PDF (free from vendor)", "steps": ["Download PowerFlex 525 Quick Start Guide","Find motor nameplate params (P031-P034)","Find Accel/Decel (P036-P037)","Find Speed Reference Source options","Find Overcurrent fault code and troubleshooting steps"]},
    "quiz": [
      {"q": "4-pole motor at 45Hz, sync speed?", "options": ["1350 RPM","900 RPM","1800 RPM","2700 RPM"], "answer": 0, "explain": "120 x 45 / 4 = 1350 RPM."},
      {"q": "OV fault most often caused by:", "options": ["Low supply voltage","Decel too fast (regen to bus)","Shorted winding","High ambient temp"], "answer": 1, "explain": "Fast decel pumps energy back to DC bus, spiking voltage."},
      {"q": "Why maintain constant V/Hz?", "options": ["Save energy","Maintain motor flux (torque capability)","Reduce harmonics","OSHA requirement"], "answer": 1, "explain": "Constant V/Hz = constant flux = rated torque at any speed."}
    ],
    "resources": [{"name":"Rockwell Literature Library","url":"https://www.rockwellautomation.com/en-us/support/documentation/literature-library.html"},{"name":"RealPars - VFDs","url":"https://www.realpars.com/"},{"name":"Siemens SIOS","url":"https://support.industry.siemens.com/"}]
  }
]
