# quiz3_data.py - extra depth questions for the Systems & Control track (modules 7-10).
# Same schema as QUIZ2: QUIZ3[module_id] = [{q, options[], answer(index), explain}, ...]
# build_academy.py extends m['quiz'] with these after QUIZ2.
QUIZ3 = {
 7: [
   {"q": "On an HMI, what is the main purpose of an alarm's ISA-18.2 'shelving' feature?",
    "options": ["Delete the alarm permanently", "Temporarily suppress a known nuisance alarm for a set time", "Raise the alarm priority", "Log the alarm to disk"],
    "answer": 1,
    "explain": "Shelving lets an operator silence a known, being-worked nuisance alarm for a limited time; it auto-returns so it can't be forgotten. It does not delete or reprioritize the alarm."},
   {"q": "A SCADA system polls 40 remote sites once per second and the historian disk fills quickly. Which change reduces storage the most without losing meaningful trend data?",
    "options": ["Poll faster", "Store on change / deadband instead of every scan", "Add more alarms", "Increase screen resolution"],
    "answer": 1,
    "explain": "Deadband (store-on-change) only records values that move more than a threshold, cutting redundant identical samples while preserving real trends - the standard historian compression approach."},
   {"q": "Which HMI color convention is correct per high-performance-HMI guidance (ISA-101)?",
    "options": ["Bright saturated colors everywhere for visibility", "Grey/low-contrast normal state, color reserved for abnormal conditions", "Red for everything running", "Flashing graphics for all live values"],
    "answer": 1,
    "explain": "High-performance HMI keeps normal operation muted/grey so that color (especially red/yellow) instantly draws the eye to genuine abnormal conditions."},
 ],
 8: [
   {"q": "PROFINET, EtherNet/IP, and Modbus TCP all run over standard Ethernet. What mainly makes an industrial network 'deterministic'?",
    "options": ["Higher cable cost", "Bounded, predictable message timing (e.g., scheduled/prioritized traffic)", "More IP addresses", "Longer cable runs"],
    "answer": 1,
    "explain": "Determinism means a message's delivery time is bounded and predictable - achieved via scheduling/prioritization (e.g., PROFINET IRT, TSN), not just raw speed."},
   {"q": "A daisy-chained device network drops all nodes downstream of one failed device. Which topology change best improves resilience?",
    "options": ["Longer cables", "A ring topology with media redundancy (e.g., DLR/MRP)", "More hubs", "Static IPs"],
    "answer": 1,
    "explain": "A managed ring (Device Level Ring, MRP) heals around a single break so downstream nodes keep communicating - unlike a plain daisy chain."},
   {"q": "What does an EtherNet/IP 'RPI' (Requested Packet Interval) set?",
    "options": ["The IP address range", "How often cyclic I/O data is exchanged", "The cable length limit", "The number of nodes"],
    "answer": 1,
    "explain": "RPI is the cyclic update rate for implicit (I/O) messaging between scanner and adapter - too fast wastes bandwidth, too slow hurts control response."},
 ],
 9: [
   {"q": "For a 6-axis industrial robot, what does the TCP (Tool Center Point) define?",
    "options": ["A network protocol", "The controlled reference point of the end effector used for motion/paths", "The motor temperature", "The safety relay state"],
    "answer": 1,
    "explain": "The TCP is the point (often at the tool tip) the controller moves and orients along programmed paths; accurate TCP calibration is essential for precise, repeatable work."},
   {"q": "A servo axis overshoots and rings when it stops. Which tuning change usually helps first?",
    "options": ["Increase proportional gain a lot", "Increase derivative/damping (or reduce excessive gain)", "Disable the encoder", "Increase the payload"],
    "answer": 1,
    "explain": "Overshoot/ringing signals too much gain or too little damping; adding derivative action or trimming gain settles the axis. Encoders and payload aren't tuning fixes."},
   {"q": "What is the difference between a robot's repeatability and its accuracy?",
    "options": ["They are identical", "Repeatability = returning to the same taught point; accuracy = hitting a commanded absolute position", "Accuracy is always worse than repeatability by design", "Repeatability only applies to SCARA robots"],
    "answer": 1,
    "explain": "Most industrial robots have excellent repeatability (same taught point) but poorer absolute accuracy; offline programming needs good accuracy, hence calibration."},
 ],
 10: [
   {"q": "A proportional-only (P) controller leaves the process short of setpoint. What is this called and what fixes it?",
    "options": ["Overshoot; add Kd", "Steady-state offset; add integral (Ki) action", "Deadtime; add Kp", "Noise; add a filter"],
    "answer": 1,
    "explain": "Pure P control leaves a residual offset because it needs error to produce output. Integral action accumulates that error and drives the offset to zero."},
   {"q": "Increasing derivative (Kd) gain on a noisy measurement often causes what problem?",
    "options": ["Slower response only", "Amplified noise and jittery output", "Steady-state offset", "Integral windup"],
    "answer": 1,
    "explain": "Derivative acts on rate-of-change, so it magnifies measurement noise into a jumpy controller output - which is why Kd is used cautiously and often filtered."},
   {"q": "What is integral windup, and a common remedy?",
    "options": ["Encoder drift; recalibrate", "Integral term accumulating while the output is saturated; use anti-windup clamping/back-calculation", "Too little Kp; raise gain", "A wiring fault; reseat cables"],
    "answer": 1,
    "explain": "When the actuator is maxed out, the integral keeps summing error, causing a big overshoot later. Anti-windup limits/holds the integral while saturated."},
 ],
}
